create extension if not exists "pgcrypto";

create table if not exists public.habits (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.habit_logs (
  id bigint generated by default as identity primary key,
  habit_id uuid not null references public.habits (id) on delete cascade,
  date date not null,
  completed boolean not null default false,
  unique (habit_id, date)
);

alter table public.habits enable row level security;
alter table public.habit_logs enable row level security;

create policy "Users can view own habits"
on public.habits
for select
using (auth.uid() = user_id);

create policy "Users can insert own habits"
on public.habits
for insert
with check (auth.uid() = user_id);

create policy "Users can update own habits"
on public.habits
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own habits"
on public.habits
for delete
using (auth.uid() = user_id);

create policy "Users can view own habit logs"
on public.habit_logs
for select
using (
  exists (
    select 1
    from public.habits
    where habits.id = habit_logs.habit_id
      and habits.user_id = auth.uid()
  )
);

create policy "Users can insert own habit logs"
on public.habit_logs
for insert
with check (
  exists (
    select 1
    from public.habits
    where habits.id = habit_logs.habit_id
      and habits.user_id = auth.uid()
  )
);

create policy "Users can update own habit logs"
on public.habit_logs
for update
using (
  exists (
    select 1
    from public.habits
    where habits.id = habit_logs.habit_id
      and habits.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.habits
    where habits.id = habit_logs.habit_id
      and habits.user_id = auth.uid()
  )
);

create policy "Users can delete own habit logs"
on public.habit_logs
for delete
using (
  exists (
    select 1
    from public.habits
    where habits.id = habit_logs.habit_id
      and habits.user_id = auth.uid()
  )
);
